### ISSUE TITLE
about repository

### ISSUE THREAD

**Issue by time-iter** [Chenxingyu1990/A-Boundary-Based-Out-of-Distribution-Classifier-for-Generalized-Zero-Shot-Learning#5]
file and commit log are inconsistent, there seems some files are missing

**Comment by Chenxingyu1990** [comment]
We just removed some logging packages and used  "print" instead.

**Comment by time-iter** [comment]
raceback (most recent call last):
  File "train.py", line 10, in <module>
    from svae_models import model_train
  File "/home/room/SU/ood/svae_models/model_train.py", line 23, in <module>
    from svae_models import classifier
ImportError: cannot import name 'classifier'

there is no such a classifier.py in folder svae_models

**Comment by Chenxingyu1990** [comment]
Sorry that we upload a wrong version. This version is an extension of previous work. It has some more functions. You can ignore the missing packages. Try to comment " from svae_models import classifier" and "from svae_models import basis_learning". Also use print instead of logging. We will fix this problem in a few days.

**Comment by Chenxingyu1990** [comment]
We have uploaded the correct version.

**Comment by time-iter** [comment]
Thanks a lot.
